name: Test Node
run-name: Deploy by @${{ github.actor }}

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: version
        run: node -v
      - name: Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: version
        run: node -v
